sudo: required
services:
  - docker

before_install:
  - docker build -t valeryia/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true valeryia/docker-react npm run test -- --coverage
